name: Test rulesets against WPGraphQL

on:
  push:
  pull_request:
  schedule:
    # Run weekly on Mondays at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch: # Allow manual triggering

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-rulesets:
    name: Test rulesets against WPGraphQL
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruleset:
          - WPGraphQL-Minimum
          - WPGraphQL-Strict
          - WPGraphQL-Extra
          - WPGraphQL-Docs
          - WPGraphQL-Core
        php: [8.4, 8.3, 8.2, 8.1, 8.0, 7.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, zip
          tools: composer:v2
          # Allow for PHP deprecation notices.
          ini-values: error_reporting = E_ALL & ~E_DEPRECATED
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate composer.json file
        run: composer validate --no-check-all --strict

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Download latest WPGraphQL from GitHub Releases
        run: |
          # Release is from https://github.com/wp-graphql/wp-graphql/releases/latest/download/wp-graphql.zip
          mkdir -p temp/wp-graphql
          curl -L -o temp/wp-graphql/wp-graphql.zip

      - name: Test ${{ matrix.ruleset }} ruleset
        id: phpcs-test
        continue-on-error: true
        run: |
          vendor/bin/phpcs --standard=./${{ matrix.ruleset }} --basepath=temp/wp-graphql -s temp/wp-graphql --report-full

      # Validate the Ruleset XML files.
      - name: Validate the WordPress rulesets
        uses: phpcsstandards/xmllint-validate@v1
        with:
          pattern: './${{ matrix.ruleset }}/*.xml'
          xsd-file: "vendor/squizlabs/php_codesniffer/phpcs.xsd"
